# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PelinaBeerChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PelinaBeerChallenge
 pod 'RxSwift'
 pod 'RxCocoa'
 pod 'Alamofire'
 pod 'AlamofireImage'
 pod 'AlamofireObjectMapper'
  target 'PelinaBeerChallengeTests' do
    inherit! :search_paths
    # Pods for testing
 pod 'Nimble'
 pod 'Quick'
  end

end
